---
backend:
  - all
input:
  input0:
    - 1
    - 3
    - 224
    - 224
  num_inputs: 1
model:
  filename: models/vgg16_traced.jit.pt
  name: vgg16
runtime:
  device: 0
  precision:
    - fp32
    - fp16
