name: Lint Code

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, review_requested, reopened]

jobs:
  cpp-linting:
    name: C++ Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Run image
        run: |
          docker run -it -d --name cpplinter -e GITHUB_TOKEN=$GITHUB_TOKEN -v $GITHUB_WORKSPACE:/workspace -v $GITHUB_EVENT_PATH:/GITHUB_EVENT.json -w /workspace docker.pkg.github.com/nvidia/trtorch/docgen:latest
          docker exec cpplinter bash -c "ls /workspace"
          docker exec cpplinter bash -c "cp /workspace/docker/WORKSPACE.docker /workspace/WORKSPACE"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        run: docker exec cpplinter bash -c "pip3 install -r /workspace/.github/scripts/requirements.txt"
      - name: Lint C++
        run: docker exec cpplinter bash -c "cd /workspace && python3 /workspace/.github/scripts/run_cpp_linter.py"

  py-linting:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Run image
        run: |
          docker run -it -d --name pylinter -e GITHUB_TOKEN=$GITHUB_TOKEN -v $GITHUB_WORKSPACE:/workspace -v $GITHUB_EVENT_PATH:/GITHUB_EVENT.json -w /workspace docker.pkg.github.com/nvidia/trtorch/docgen:latest
          docker exec pylinter bash -c "cp /workspace/docker/WORKSPACE.docker /workspace/WORKSPACE"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        run: |
          docker exec pylinter bash -c "pip3 install -r /workspace/.github/scripts/requirements.txt"
      - name: Lint Python
        run: docker exec pylinter bash -c "cd /workspace && python3 /workspace/.github/scripts/run_cpp_linter.py"
